#!/bin/bash

# Output file
AUTHORS_FILE="AUTHORS"

# Header for the AUTHORS file
echo "# File @generated by generate-authors.sh. DO NOT EDIT." > "$AUTHORS_FILE"
echo "# This file lists all contributors to the repository." >> "$AUTHORS_FILE"
echo "# See generate-authors.sh to make modifications." >> "$AUTHORS_FILE"
echo "" >> "$AUTHORS_FILE"

# Use Git to get a list of contributors
git log --format='%aN <%aE>' | sort -u >> "$AUTHORS_FILE"

echo "AUTHORS file generated successfully."

